local M = {}

function M.get(p, opts)
	local bg_float = opts.transparent and "NONE" or p.bg_float
	return {
		SnacksNormal = { fg = p.fg, bg = bg_float },
		SnacksNormalNC = { fg = p.fg_muted, bg = bg_float },
		SnacksBorder = { fg = p.border, bg = bg_float },
		SnacksWinBar = { fg = p.fg, bg = bg_float, bold = true },
		SnacksWinBarNC = { fg = p.fg_muted, bg = bg_float },
		SnacksWinSeparator = { fg = p.border, bg = bg_float },
		SnacksTitle = { fg = p.fg, bg = bg_float, bold = true },
		SnacksFooter = { fg = p.fg_muted, bg = bg_float },
		SnacksFooterKey = { fg = p.pink, bg = bg_float, bold = true },
		SnacksFooterDesc = { fg = p.fg_muted, bg = bg_float },
		SnacksWinKey = { fg = p.pink, bold = true },
		SnacksWinKeySep = { fg = p.fg_subtle },
		SnacksWinKeyDesc = { fg = p.fg },
		SnacksBackdrop = { bg = p.bg, blend = 60 },
		SnacksNotifierInfo = { fg = p.info },
		SnacksNotifierWarn = { fg = p.warning },
		SnacksNotifierError = { fg = p.error },
		SnacksNotifierDebug = { fg = p.fg_muted },
		SnacksNotifierTrace = { fg = p.fg_subtle },
		SnacksNotifierBorderInfo = { fg = p.info },
		SnacksNotifierBorderWarn = { fg = p.warning },
		SnacksNotifierBorderError = { fg = p.error },
		SnacksNotifierBorderDebug = { fg = p.fg_muted },
		SnacksNotifierBorderTrace = { fg = p.fg_subtle },
		SnacksNotifierIconInfo = { fg = p.info },
		SnacksNotifierIconWarn = { fg = p.warning },
		SnacksNotifierIconError = { fg = p.error },
		SnacksNotifierIconDebug = { fg = p.fg_muted },
		SnacksNotifierIconTrace = { fg = p.fg_subtle },
		SnacksDashboardNormal = { fg = p.fg, bg = opts.transparent and "NONE" or p.bg },
		SnacksDashboardDesc = { fg = p.fg_muted },
		SnacksDashboardFile = { fg = p.blue },
		SnacksDashboardDir = { fg = p.fg_muted },
		SnacksDashboardFooter = { fg = p.fg_subtle, italic = true },
		SnacksDashboardHeader = { fg = p.blue },
		SnacksDashboardIcon = { fg = p.blue },
		SnacksDashboardKey = { fg = p.pink },
		SnacksDashboardTerminal = { fg = p.fg },
		SnacksDashboardSpecial = { fg = p.purple },
		SnacksPickerTitle = { fg = p.bg, bg = p.blue, bold = true },
		SnacksPickerBorder = { fg = p.border, bg = bg_float },
	}
end

return M
